apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  namespace: demo
  labels:
    app: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
        - name: socket
          image: ratuliit42/chat-app:v2
          resources:
            limits:
              cpu: 80m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 80Mi
          ports:
          - name: socketio
            containerPort: 3000
          # - name: http
          #   containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: socket
  namespace: demo
  labels:
    app: socket
spec:
  type: NodePort
  ports:
  # - port: 8081
  #   targetPort: http
  #   name: http
  #   protocol: TCP
  - port: 3000
    targetPort: socketio
    name: socketio
    protocol: TCP
  selector:
    app: socket
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: socket
  namespace: demo
  labels:
    release: prometheus
spec:
  endpoints:
  - port: socketio
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app: socket
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   namespace: demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx-server
#   template:
#     metadata:
#       annotations:
#         prometheus.io/path: "/metrics"
#         prometheus.io/scrape: "true"
#         prometheus.io/port: "9913"
#       labels:
#         app: nginx-server
#     spec:
#       containers:
#       - name: nginx-demo
#         image: sophos/nginx-vts-exporter
#         imagePullPolicy: Always
#         resources:
#           limits:
#             cpu: 80m
#             memory: 100Mi
#           requests:
#             cpu: 50m
#             memory: 80Mi
#         ports:
#         - containerPort: 9913
#           name: scrape
#         - containerPort: 80
#           name: http
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
#   namespace: demo
# spec:
#   ports:
#   - port: 9913
#     targetPort: 9913
#     name: scrape
#   - port: 80
#     targetPort: 80
#     name: http
#   selector:
#     app: nginx-server
#   type: NodePort
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: nginx-server
#   namespace: demo
#   labels:
#     team: devops
# spec:
#   endpoints:
#   - port: http
#     interval: 5s
#   namespaceSelector:
#     matchNames:
#     - demo
#   selector:
#     matchLabels:
#       app: nginx-server