---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  namespace: demo
  labels:
    app: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
        - name: socket
          image: ratuliit42/chat-app:fix
          resources:
            limits:
              cpu: 80m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 80Mi
          ports:
          - name: socketio
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: socket
  namespace: demo
  labels:
    app: socket
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: socketio
    name: socketio
    protocol: TCP
  selector:
    app: socket
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: socket
  namespace: demo
  labels:
    release: prometheus
spec:
  endpoints:
  - port: socketio
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app: socket
