prometheus:
  url: http://prometheus-operated.default.svc.cluster.local
  port: 9090

rules:
  custom:
  - seriesQuery: '{__name__=~"socket_io_connected",namespace!="",pod!=""}'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: ^(.*)
      as: "socket_io_connected"
    metricsQuery: (avg(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>))